#
# Executes commands at logout.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# WHY?????? -NP
## Print the message.
#cat <<-EOF
#
#Thank you. Come again!
#  -- Dr. Apu Nahasapeemapetilon
#EOF
